spring.datasource.url=${DB_URL:jdbc:postgresql://aws-0-eu-west-1.pooler.supabase.com:6543/postgres?sslmode=require&pgbouncer=true}
spring.datasource.username=${DB_USER:postgres.lclmkuhlwujdhujrwaus}
spring.datasource.password=${DB_PASSWORD:tAPFl5Urya67N8gc}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.jdbc.use_get_generated_keys=false

server.port=8080
spring.web.resources.static-locations=file:../NewFrontEndProject/,classpath:/static/

ors.api.key=${ORS_API_KEY:eyJvcmciOiI1YjNjZTM1OTc4NTExMTAwMDFjZjYyNDgiLCJpZCI6IjM1ZDQ1ZDc2MjJiMDQzMmM4MTQ3ZjQ3YWI2Y2I5NmY4IiwiaCI6Im11cm11cjY0In0=}
warehouse.address=${WAREHOUSE_ADDRESS:Lagervej 1, 2600 Glostrup}    

spring.datasource.hikari.data-source-properties.prepareThreshold=0
<dependency>
<groupId>org.springframework.boot</groupId>
<artifactId>spring-boot-starter-test</artifactId>
<scope>test</scope>
</dependency>